### ISSUE TITLE
Не заметный баг в JS файле

### ISSUE THREAD

**Issue by alex-lenk** [danyaPostfactum/modx-ckeditor#30]
Здравствуйте. Хотел бы сообщить баг, который проявляется на мобильных устройствах и в эмуляторах мобильных устройствах:
1. http://joxi.ru/823jW0QiK1K3mO этот эмулятор можно увидеть в браузере chrome и только тогда, когда редактируешь ресурс.
2. http://joxi.ru/zAN5Mxlsx3xo29

Дело в том, что я написал плагин для админки, который на мобильных устройствах позволит адаптировать административную часть и можно будет со смартфона управлять сайтом.

Именно ваш ckeditor является адаптивным и отличным визуальным редактором!
А вот как выглядит TinyMCE http://joxi.ru/DmBEg6kuP3PXrP

Мой маленький плагин https://github.com/alex-lenk/adaptivePanel (естественно он будет дополняться).

**Comment by danyaPostfactum** [comment]
А как баг воспроизвести? Включил эмулятор, перезагрузил страницу - ошибок нет.
Нужно установить ваш плагин?

**Comment by alex-lenk** [comment]
http://joxi.ru/gmve1kGfBl3era

Вот чистый тестовый сайт и там установлен только один плагин ckeditor
http://s3738.h2.modhost.pro/manager/
s3738
A8VT3pVJhLcY

**Comment by danyaPostfactum** [comment]
CKEditor отключается, не находя версию браузера в своем белом списке.
http://stackoverflow.com/questions/30788527/ckeditor-4-4-7-does-not-show-up-on-any-mobile-browsers

В новых версиях CKEditor вроде бы проблему решили, так что мне нужно будет обновить ckeditor (давно пора).

**Comment by alex-lenk** [comment]
ура, спасибо большое. Буду ждать нового реализа от вас.
